name: Continuous Integration
on:
  push: 
    paths-ignore:
      - 'README.md'

  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --tag todo-app:test --target test .
    - run: docker run todo-app:test
    
  deploy:
    name: Push to Docker Hub and Trigger App Service for Deployment
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/Mod9CD' }} 
    steps:
    - uses: actions/checkout@v4
    - run: echo hello deploy
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_NASHU }}
        password: ${{ secrets.DOCKER_HUB_DUPASSWORD }}